clear all
clc
close all

%MATRICE
A = [1,pi,exp(1);-3,7,4/3]

%MATRICE IDENTITA'
I = eye(5)

%MATRICI DI ZERI 3 RIGHE 4 COLONNE
O = zeros(3,4)   

%MATRICE COSTANTE CON TUTTI 5
K = 5* ones(6,7)

%MATRICE DI HILBERT
H = hilb(7)

%OPERAZIONI TRA MATRICI
A = ones(3,4)
B = A;

SUM = A+B  %SOLO SE SONO UGUALI DI DIMENSIONI RIGHE COLONNE
K = 5*A %MOLTIPLICAZIONE PER COSTANTE
%P = A*B %NON FUNZIONA PERCHE NCOLONNEPRIMA != NRIGHESECONDA

%TRASPOSTA 
BTRASPOSTA = B';

%PRODOTTO
P=A*BTRASPOSTA