clear all
clc
close all

%SCRITTURE EQIVALENTI
A=[1:4,5:8,9:12]
A = [1,2,3,4;5,6,7,8;9,10,11,12]

%DIMENSIONE A (RETURNA RIGHE E COLONNE) PER VETTORI LENGTH
size(A)

%ALTRI COMANDI
A(1:2,4)  %QUARTO ELEMENTO DELLE RIGHE DA 1 A 2

A(:,3)  % TERZO ELEMENTO DI TUTTE LE RIGHE

A(1:2,:) %PRIMA E SECONDA RIGA

A(:,[2 4]) %COLONNA 2  E 4 DI TUTTE LE RIGHE

A([2 ,3 ,3],:) %RIGHE 2 E 3 E 3 UN ALTRA VOLTA 

A(3,2) = A(1,1) %ASSEGNA ALL ELEMENTO DI RIGA 3 E COLONNA 2 CIO' CHE STA IN RIGA 1 COLONNA 1

A(1:2,4) =zeros(2,1) %ASSEGNA ALLA 4 COLONNA DELLE RIGHE DA 1 A 2 LA MATRICE DI ZERI 2 RIGHE 1 COLONNA (NON POSSO METTERE VETTORE RIGA)

A(2,:)=A(2,:)-A(2,1)/A(1,1)*A(1,:)  %ASSEGNA ALLA SECONDA RIGA LE OPREAZIONI DI (SECONDA_RIGA) =-5/1*(PRIMA_RIGA)