%MATRICE PUO INDICIZZARE DIAGONALE

%DIAGONALE PRINCIPALE =0
%DIAGONALE SOPRA = 1
%DIAGONALE SOTTO = -1

B = zeros(10,10)

%CREO VETTORI
v1 = 5*(ones(10,1))  
v2 = 3*(ones(9,1))
v3 = -1*(ones(9,1))

%CREO 3 MATRICI DIAGONALE
ADIAG = diag(v1,0)
ASUP = diag(v2,1)
AINF = diag(v3,-1)

%SOMMA MATRICI
B = ADIAG+ASUP+AINF

