clear all
clc
close all
A = [1,2,3;2,1,3;1,1,2;0,1,1;3,1,4];
B = [1,-2,2,3,0]';

R=rank(A)  %RANGO NON È MASSIMO (2) DOVREBBE ESSERE 3

%SICCOME RANK(A) NON E'0 MASSIMO ESISTONO INFINITE SOLUZIONI PER CUI E'
%MINIMO ||Ax-B||  ESISTONO IFINITE SOLUZIONI TALE PER CUI È MINIMA LA NORMA
%DEL RESIDUO E SI RICORDI CHE C'E' N'E' UNICA SOLUZIONE MINIMA LA JORMA
%EUCLIDEA
C= A\B