v = [-0.0000,-0.4472,0.8944]'

for i=1:4
    A = [1 2 i ; 3 2 1 ; i 4 2];
    dimIm = rank(A);
    dimKer = 3-dimIm;
    ris = A*v

end


%LE PRIME TRE AFFERMAZIONI SONO FALSE

%POICHE RIS A*v = 0 SIGNIFICA CHE V APPARTIENE AL KERNEL DELLA MATRICE DI
%PARTENZA IN QUANTO GLI ELEMENTI DEL KERNEL SONO ELEMENTI (VETTORI) NON
%NULLI CHE CI DANNO ZERO SE MESSI NELLA A.L.